// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using aaaSystemsApi;

#nullable disable

namespace aaaSystemsApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230225000425_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.1");

            modelBuilder.Entity("aaaSystemsCommon.Entity.Dialog", b =>
                {
                    b.Property<long>("ChatId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsNeedAnswer")
                        .HasColumnType("INTEGER");

                    b.HasKey("ChatId");

                    b.ToTable("Dialogs");
                });

            modelBuilder.Entity("aaaSystemsCommon.Entity.DialogMessage", b =>
                {
                    b.Property<int>("MessageId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ChatId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("TEXT");

                    b.HasKey("MessageId");

                    b.HasIndex("ChatId");

                    b.ToTable("DialogMessages");
                });

            modelBuilder.Entity("aaaSystemsCommon.Entity.Sender", b =>
                {
                    b.Property<long>("ChatId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("PK")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.HasKey("ChatId");

                    b.HasIndex("PK")
                        .IsUnique();

                    b.ToTable("Senders");
                });

            modelBuilder.Entity("aaaSystemsCommon.Entity.DialogMessage", b =>
                {
                    b.HasOne("aaaSystemsCommon.Entity.Dialog", null)
                        .WithMany()
                        .HasForeignKey("ChatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("aaaSystemsCommon.Entity.Sender", b =>
                {
                    b.HasOne("aaaSystemsCommon.Entity.Dialog", null)
                        .WithOne()
                        .HasForeignKey("aaaSystemsCommon.Entity.Sender", "PK")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
